name: "Grep"
description: |
  Run grep and submit results, and additional details, as Annotations
author: "Freckle"
inputs:
  patterns:
    description: "String of Yaml describing a list of Patterns"
    required: true
  only-changed:
    description: "Only operate on changed files"
    required: true
    default: "true"
  create-new-check:
    description: "Create a new Check for our annotations?"
    required: true
    default: "false"
  failure-threshold:
    description: "Fail on any annotations at or above this level"
    required: true
    default: "failure"
  github-token:
    description: "Override GitHub token, if necessary"
    required: true
    default: "${{ github.token }}"

runs:
  using: "node16"
  main: "dist/index.js"
