name: "Grep"
description: |
  Run grep and submit results, and additional details, as Annotations
author: "Freckle"
inputs:
  patterns:
    description: "String of Yaml describing a list of Patterns"
    required: true
  only-changed:
    description: "Only operate on changed files"
    required: true
    default: "true"
  github-token:
    description: "GitHub token to use, default is secrets.GITHUB_TOKEN"
    required: true
    default: "${{ secrets.GITHUB_TOKEN }}"

runs:
  using: "node12"
  main: "dist/index.js"
